/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package academico.gui;
/**
 *
 * @author AC_Inc
 */

import controlador.EstudianteBO;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import modelo.Estudiante;
import javax.swing.table.DefaultTableModel;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import modelo.LeerBD;
import java.util.Date;


public class DescuentosVista extends javax.swing.JDialog {


    /**
     * Creates new form CrearEstudiante
     */
    
    ArrayList<Estudiante> listaEstudiante = new ArrayList<>();
    EstudianteBO estudianteBO;
    Estudiante estudiante;
    LeerBD leerBD;
    
    
    public DescuentosVista(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        estudianteBO = new EstudianteBO();
        listarTbl();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        estudiantesTbl = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        valorLbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Crear Nuevo Estudiante");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("REPORTE DE DESCUENTOS");

        estudiantesTbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                estudiantesTblMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(estudiantesTbl);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("TOTAL DESCUENTOS:");

        valorLbl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        valorLbl.setText("VALOR");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1039, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(valorLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel6)
                    .addComponent(valorLbl))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 463, Short.MAX_VALUE)
                .addGap(40, 40, 40))
        );

        setSize(new java.awt.Dimension(1081, 605));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void estudiantesTblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_estudiantesTblMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_estudiantesTblMouseClicked

    
    private void listarTbl (){
           Double suma;
           estudiantesTbl.setModel(estudianteBO.getModeloDescuento());
           suma = estudianteBO.sumar();
           valorLbl.setText(String.valueOf(suma));
    }    
    

    private boolean validarId (String id){
        return estudianteBO.validarId(id);
    }


    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable estudiantesTbl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel valorLbl;
    // End of variables declaration//GEN-END:variables
}
